// Code generated by "stringer -type=Direction -trimprefix=Dir"; DO NOT EDIT.

package data

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DirN-0]
	_ = x[DirNNE-1]
	_ = x[DirNE-2]
	_ = x[DirENE-3]
	_ = x[DirE-4]
	_ = x[DirESE-5]
	_ = x[DirSE-6]
	_ = x[DirSSE-7]
	_ = x[DirS-8]
	_ = x[DirSSW-9]
	_ = x[DirSW-10]
	_ = x[DirWSW-11]
	_ = x[DirW-12]
	_ = x[DirWNW-13]
	_ = x[DirNW-14]
	_ = x[DirNNW-15]
	_ = x[DirCalm-16]
	_ = x[DirUnknown-17]
}

const _Direction_name = "NNNENEENEEESESESSESSSWSWWSWWWNWNWNNWCalmUnknown"

var _Direction_index = [...]uint8{0, 1, 4, 6, 9, 10, 13, 15, 18, 19, 22, 24, 27, 28, 31, 33, 36, 40, 47}

func (i Direction) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Direction_index)-1 {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[idx]:_Direction_index[idx+1]]
}
