// Code generated by "stringer -type=Weather -trimprefix=Weather"; DO NOT EDIT.

package data

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WeatherSunny-0]
	_ = x[WeatherCloudy-1]
	_ = x[WeatherRainy-2]
	_ = x[WeatherOther-3]
}

const _Weather_name = "SunnyCloudyRainyOther"

var _Weather_index = [...]uint8{0, 5, 11, 16, 21}

func (i Weather) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Weather_index)-1 {
		return "Weather(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Weather_name[_Weather_index[idx]:_Weather_index[idx+1]]
}
